// Roadmap data — 任務/詳情/方法覆寫/方法說明/標籤定義
  export const TASKS = {
  "df_event_spec": {"id":"df_event_spec","milestone":"M1","is_anchor":true,"lane":"data_foundation","laneTitle":"資料基礎與事件觀測","sprint":"Sprint 4–5","title":"事件追蹤規範設計","tags":["D","O"],"phase":"Phase 1","deps":[],"enables":["df_search_events","df_purchase_events","df_browse_events","df_marketing_events","df_login_events","search_beta"],"validation":["事件覆蓋率與漏斗可追蹤","搜尋、曝光、點擊、收藏、booking_start 可回收","ID Mapping 與跨渠道回饋可逐步銜接"],"limit":"資料準備階段承載可觀測與可回饋基礎；資料表、欄位、API、權限與治理規格由資料治理或系統設計文件承接。","initial":"完成事件規範、關鍵行為補點與基本成效回收，不在此文件展開欄位、表設計或 API payload。","method":"Event Taxonomy / Funnel Mapping / Naming Convention / Event QA / Data Contract","output":"可執行事件規範、事件命名規則、漏斗對照與埋點驗收清單。"},
  "df_search_events": {"id":"df_search_events","milestone":"M1","is_anchor":false,"lane":"data_foundation","laneTitle":"資料基礎與事件觀測","sprint":"Sprint 4–5","title":"搜尋相關事件埋設","tags":["D","O"],"phase":"Phase 1","deps":["df_event_spec"],"enables":["search_beta","search_trial","search_app_launch"],"validation":["事件覆蓋率與漏斗可追蹤","搜尋、曝光、點擊、收藏、booking_start 可回收","ID Mapping 與跨渠道回饋可逐步銜接"],"limit":"資料準備階段承載可觀測與可回饋基礎；資料表、欄位、API、權限與治理規格由資料治理或系統設計文件承接。","initial":"完成事件規範、關鍵行為補點與基本成效回收，不在此文件展開欄位、表設計或 API payload。","method":"Search Event Schema / Query Log Structuring / SERP Exposure Tracking / Zero-result Tracking","output":"搜尋 query log、搜尋曝光、點擊、改搜與查無結果回饋資料。"},
  "df_purchase_events": {"id":"df_purchase_events","milestone":"M1","is_anchor":false,"lane":"data_foundation","laneTitle":"資料基礎與事件觀測","sprint":"Sprint 4–5","title":"購買相關事件埋設（補）","tags":["D","O"],"phase":"Phase 1","deps":["df_event_spec"],"enables":["df_decision_info","df_id_mapping","reco_hot","act_stage_label","ads_capi","dt_posttrip"],"validation":["事件覆蓋率與漏斗可追蹤","搜尋、曝光、點擊、收藏、booking_start 可回收","ID Mapping 與跨渠道回饋可逐步銜接"],"limit":"資料準備階段承載可觀測與可回饋基礎；資料表、欄位、API、權限與治理規格由資料治理或系統設計文件承接。","initial":"完成事件規範、關鍵行為補點與基本成效回收，不在此文件展開欄位、表設計或 API payload。","method":"Conversion Funnel Mapping / Booking Event Schema / Attribution Feedback / Data Quality Check","output":"booking_start、訂單與成交回饋事件，用於推薦、活化與投放成效閉環。"},
  "df_browse_events": {"id":"df_browse_events","milestone":"M1","is_anchor":false,"lane":"data_foundation","laneTitle":"資料基礎與事件觀測","sprint":"Sprint 5–6","title":"瀏覽相關事件埋設（補）","tags":["D","O"],"phase":"Phase 1","deps":["df_event_spec"],"enables":["df_cold_start","df_decision_info","df_id_mapping","reco_hot","reco_similar","reco_segment_content","reco_trend","reco_infinite","act_stage_label"],"validation":["事件覆蓋率與漏斗可追蹤","搜尋、曝光、點擊、收藏、booking_start 可回收","ID Mapping 與跨渠道回饋可逐步銜接"],"limit":"資料準備階段承載可觀測與可回饋基礎；資料表、欄位、API、權限與治理規格由資料治理或系統設計文件承接。","initial":"完成事件規範、關鍵行為補點與基本成效回收，不在此文件展開欄位、表設計或 API payload。","method":"Browse Event Schema / Engagement Depth / Product View Tracking / Signal Aggregation","output":"瀏覽、停留、收藏、商品互動與內容深度訊號。"},
  "df_marketing_events": {"id":"df_marketing_events","milestone":"M1","is_anchor":false,"lane":"data_foundation","laneTitle":"資料基礎與事件觀測","sprint":"Sprint 6–7","title":"行銷相關事件埋設","tags":["D","O"],"phase":"Phase 1","deps":["df_event_spec"],"enables":["act_segment_push","act_script_push","ads_capi"],"validation":["事件覆蓋率與漏斗可追蹤","搜尋、曝光、點擊、收藏、booking_start 可回收","ID Mapping 與跨渠道回饋可逐步銜接"],"limit":"資料準備階段承載可觀測與可回饋基礎；資料表、欄位、API、權限與治理規格由資料治理或系統設計文件承接。","initial":"完成事件規範、關鍵行為補點與基本成效回收，不在此文件展開欄位、表設計或 API payload。","method":"Campaign Event Schema / UTM Mapping / Push Interaction Tracking / Channel Feedback","output":"行銷互動、推播點擊、站外回流與 campaign 回饋資料。"},
  "df_login_events": {"id":"df_login_events","milestone":"M1","is_anchor":false,"lane":"data_foundation","laneTitle":"資料基礎與事件觀測","sprint":"Sprint 6–7","title":"登入註冊相關事件埋設（補）","tags":["D","O"],"phase":"Phase 1","deps":["df_event_spec"],"enables":["df_cold_start","df_id_mapping","reco_segment_content","act_segment_push","ads_capi","ads_signal_gateway"],"validation":["事件覆蓋率與漏斗可追蹤","搜尋、曝光、點擊、收藏、booking_start 可回收","ID Mapping 與跨渠道回饋可逐步銜接"],"limit":"資料準備階段承載可觀測與可回饋基礎；資料表、欄位、API、權限與治理規格由資料治理或系統設計文件承接。","initial":"完成事件規範、關鍵行為補點與基本成效回收，不在此文件展開欄位、表設計或 API payload。","method":"Identity Event Mapping / Login Funnel Tracking / Consent State Mapping / Member Linking","output":"登入註冊漏斗、會員關聯、同意狀態與匿名轉會員銜接資料。"},
  "df_cold_start": {"id":"df_cold_start","milestone":"M1","is_anchor":false,"lane":"data_foundation","laneTitle":"資料基礎與事件觀測","sprint":"Sprint 8–9","title":"冷啟動旅遊偏好收集","tags":["D","O"],"phase":"Phase 1","deps":["df_browse_events","df_login_events"],"enables":["act_stage_label"],"validation":["事件覆蓋率與漏斗可追蹤","搜尋、曝光、點擊、收藏、booking_start 可回收","ID Mapping 與跨渠道回饋可逐步銜接"],"limit":"資料準備階段承載可觀測與可回饋基礎；資料表、欄位、API、權限與治理規格由資料治理或系統設計文件承接。","initial":"完成事件規範、關鍵行為補點與基本成效回收，不在此文件展開欄位、表設計或 API payload。","method":"Preference Questionnaire / Progressive Profiling / Cold-start Feature Encoding / Rule-based Preference Mapping","output":"冷啟動偏好特徵、旅遊主題偏好與初始推薦候選條件。"},
  "df_decision_info": {"id":"df_decision_info","milestone":"M1","is_anchor":false,"lane":"data_foundation","laneTitle":"資料基礎與事件觀測","sprint":"Sprint 8–9","title":"決策資訊收集","tags":["D","O"],"phase":"Phase 1","deps":["df_browse_events","df_purchase_events"],"enables":["reco_context","cross_decision_pref","act_active_grade"],"validation":["事件覆蓋率與漏斗可追蹤","搜尋、曝光、點擊、收藏、booking_start 可回收","ID Mapping 與跨渠道回饋可逐步銜接"],"limit":"資料準備階段承載可觀測與可回饋基礎；資料表、欄位、API、權限與治理規格由資料治理或系統設計文件承接。","initial":"完成事件規範、關鍵行為補點與基本成效回收，不在此文件展開欄位、表設計或 API payload。","method":"Decision Attribute Collection / Preference Feature Engineering / Context Labeling / Intent Feature Mapping","output":"決策類型、旅遊動機、價格敏感、同行者與行前情境特徵。"},
  "df_id_mapping": {"id":"df_id_mapping","milestone":"M1","is_anchor":false,"lane":"data_foundation","laneTitle":"資料基礎與事件觀測","sprint":"Sprint 12–13","title":"定期規整及清理使用者 ID（ID Mapping）","tags":["D","O"],"phase":"Phase 1","deps":["df_login_events","df_purchase_events","df_browse_events"],"enables":["act_ai_audience"],"validation":["事件覆蓋率與漏斗可追蹤","搜尋、曝光、點擊、收藏、booking_start 可回收","ID Mapping 與跨渠道回饋可逐步銜接"],"limit":"資料準備階段承載可觀測與可回饋基礎；資料表、欄位、API、權限與治理規格由資料治理或系統設計文件承接。","initial":"完成事件規範、關鍵行為補點與基本成效回收，不在此文件展開欄位、表設計或 API payload。","method":"Identity Resolution / Device-to-User Stitching / Merge Rules / Data Quality Check","output":"使用者 ID 關聯表、匿名與會員映射、合併規則與清理結果。"},
  "search_beta": {"id":"search_beta","milestone":"M3","is_anchor":false,"lane":"ai_search","laneTitle":"AI 搜尋機制","sprint":"Sprint 5–6","title":"AI 產品搜尋 Beta","tags":["S","H"],"phase":"Phase 3","deps":["df_search_events","df_event_spec"],"enables":["search_trial","search_vector"],"validation":["搜尋結果頁到商品詳情頁 CTR","查無結果率與 zero-click rate","改搜率、搜尋後 booking_start 率"],"limit":"AI 搜尋屬搜尋理解與排序能力；AI 互動服務或 Agent Workflow 由 AI 互動服務層承接。","initial":"先以 Query Understanding、Keyword Retrieval、Vector Retrieval、Filter 與 Reranking 的小流量驗證為主。","method":"BM25 / Synonym Expansion / Query Rewrite / NER / Rule-based Facet Mapping","output":"Beta 版搜尋理解結果、改寫查詢、facet 條件與候選商品池。"},
  "search_trial": {"id":"search_trial","milestone":"M3","is_anchor":false,"lane":"ai_search","laneTitle":"AI 搜尋機制","sprint":"Sprint 7","title":"AI 搜尋小流量試營運","tags":["S","H"],"phase":"Phase 3","deps":["search_beta","df_search_events"],"enables":["search_app_launch"],"validation":["搜尋結果頁到商品詳情頁 CTR","查無結果率與 zero-click rate","改搜率、搜尋後 booking_start 率"],"limit":"AI 搜尋屬搜尋理解與排序能力；AI 互動服務或 Agent Workflow 由 AI 互動服務層承接。","initial":"先以 Query Understanding、Keyword Retrieval、Vector Retrieval、Filter 與 Reranking 的小流量驗證為主。","method":"Search Quality Evaluation / A/B Testing / Relevance Feedback / Zero-result Analysis","output":"小流量成效觀測、搜尋品質回饋、zero-click 與改搜分析。"},
  "search_vector": {"id":"search_vector","milestone":"M3","is_anchor":false,"lane":"ai_search","laneTitle":"AI 搜尋機制","sprint":"Sprint 7","title":"Vector Retrieval 接入 Hybrid Search","tags":["S","H"],"phase":"Phase 3","deps":["search_beta"],"enables":["search_app_launch","search_web_launch","reco_similar"],"validation":["搜尋結果頁到商品詳情頁 CTR","查無結果率與 zero-click rate","改搜率、搜尋後 booking_start 率"],"limit":"AI 搜尋屬搜尋理解與排序能力；AI 互動服務或 Agent Workflow 由 AI 互動服務層承接。","initial":"先以 Query Understanding、Keyword Retrieval、Vector Retrieval、Filter 與 Reranking 的小流量驗證為主。","method":"Embedding Retrieval / ANN Search / Hybrid Fusion / Candidate Recall Evaluation","output":"向量召回候選池、keyword + vector 混合召回結果與召回品質指標。"},
  "search_app_launch": {"id":"search_app_launch","milestone":"M3","is_anchor":true,"lane":"ai_search","laneTitle":"AI 搜尋機制","sprint":"Sprint 8–9","title":"AI 搜尋正式上線（App 2.0）","tags":["S","H"],"phase":"Phase 3","deps":["search_trial","search_vector","df_search_events"],"enables":["search_web_launch","reco_infinite","dt_pretrip"],"validation":["搜尋結果頁到商品詳情頁 CTR","查無結果率與 zero-click rate","改搜率、搜尋後 booking_start 率"],"limit":"AI 搜尋屬搜尋理解與排序能力；AI 互動服務或 Agent Workflow 由 AI 互動服務層承接。","initial":"先以 Query Understanding、Keyword Retrieval、Vector Retrieval、Filter 與 Reranking 的小流量驗證為主。","method":"Hybrid Search / Availability Filter / Facet Filter / Learning-to-Rank / Feature Flag Rollout","output":"App 2.0 正式搜尋結果、排序分數、可售條件過濾與上線觀測資料。"},
  "search_web_launch": {"id":"search_web_launch","milestone":"M3","is_anchor":false,"lane":"ai_search","laneTitle":"AI 搜尋機制","sprint":"Sprint 10–11","title":"AI 搜尋 Web 上線規劃","tags":["S","H"],"phase":"Phase 3","deps":["search_app_launch","search_vector"],"enables":["dt_intratrip"],"validation":["搜尋結果頁到商品詳情頁 CTR","查無結果率與 zero-click rate","改搜率、搜尋後 booking_start 率"],"limit":"AI 搜尋屬搜尋理解與排序能力；AI 互動服務或 Agent Workflow 由 AI 互動服務層承接。","initial":"先以 Query Understanding、Keyword Retrieval、Vector Retrieval、Filter 與 Reranking 的小流量驗證為主。","method":"Web Search Integration / Hybrid Search / Ranking Calibration / Search Analytics","output":"Web 搜尋上線規劃、排序校準規則、跨裝置搜尋品質觀測。"},
  "reco_hot": {"id":"reco_hot","milestone":"M2","is_anchor":true,"lane":"recommendation","laneTitle":"推薦機制","sprint":"Sprint 5–6","title":"每日熱門商品機制優化（累積 / 指數）","tags":["R","B","I"],"phase":"Phase 2 → 4","deps":["df_browse_events","df_purchase_events"],"enables":["reco_segment_content","reco_trend"],"validation":["推薦曝光後 CTR 是否高於原排序商品","推薦商品進入詳情頁、收藏、booking_start 的增量","熱門分數是否排除高曝光污染"],"limit":"即時推薦屬後續成熟能力；初期先以 batch / session-based 能力驗證商品池、排序與回饋，再逐步銜接 event streaming、online feature 與低延遲服務。","initial":"初期以 batch / session-based 驗證商品池、排序與回饋，後續逐步銜接 full real-time 能力。","method":"Time-decay Popularity / Wilson Score / Bayesian Smoothing / Exposure Correction","output":"熱門商品分數、曝光修正後排序與熱門推薦商品池。"},
  "reco_similar": {"id":"reco_similar","milestone":"M2","is_anchor":false,"lane":"recommendation","laneTitle":"推薦機制","sprint":"Sprint 7–8","title":"相似商品推薦","tags":["R","B","I"],"phase":"Phase 2 → 4","deps":["df_browse_events","search_vector"],"enables":["reco_infinite","cross_related"],"validation":["推薦曝光後 CTR 是否高於原排序商品","推薦商品進入詳情頁、收藏、booking_start 的增量","熱門分數是否排除高曝光污染"],"limit":"即時推薦屬後續成熟能力；初期先以 batch / session-based 能力驗證商品池、排序與回饋，再逐步銜接 event streaming、online feature 與低延遲服務。","initial":"初期以 batch / session-based 驗證商品池、排序與回饋，後續逐步銜接 full real-time 能力。","method":"Content-based Similarity / Embedding Similarity / Item-to-Item CF / Similarity Thresholding","output":"相似商品清單、替代探索候選與相似理由。"},
  "reco_segment_content": {"id":"reco_segment_content","milestone":"M2","is_anchor":false,"lane":"recommendation","laneTitle":"推薦機制","sprint":"Sprint 8–9","title":"分眾內容推薦（ID-based，手動條件控版位）","tags":["R","B","I"],"phase":"Phase 2 → 4","deps":["df_login_events","df_browse_events","reco_hot"],"enables":["reco_context"],"validation":["推薦曝光後 CTR 是否高於原排序商品","推薦商品進入詳情頁、收藏、booking_start 的增量","熱門分數是否排除高曝光污染"],"limit":"即時推薦屬後續成熟能力；初期先以 batch / session-based 能力驗證商品池、排序與回饋，再逐步銜接 event streaming、online feature 與低延遲服務。","initial":"初期以 batch / session-based 驗證商品池、排序與回饋，後續逐步銜接 full real-time 能力。","method":"Rule-based Segmentation / ID-based Audience Matching / Content-based Recommendation / Manual Slot Control","output":"ID-based 分眾商品池、版位控管條件與分眾推薦清單。"},
  "reco_trend": {"id":"reco_trend","milestone":"M4","is_anchor":false,"lane":"recommendation","laneTitle":"推薦機制","sprint":"Sprint 10–11","title":"趨勢商品機制優化（外部趨勢話題與促銷時機）","tags":["R","B","I"],"phase":"Phase 2 → 4","deps":["reco_hot","df_browse_events"],"enables":[],"validation":["推薦曝光後 CTR 是否高於原排序商品","推薦商品進入詳情頁、收藏、booking_start 的增量","熱門分數是否排除高曝光污染"],"limit":"即時推薦屬後續成熟能力；初期先以 batch / session-based 能力驗證商品池、排序與回饋，再逐步銜接 event streaming、online feature 與低延遲服務。","initial":"初期以 batch / session-based 驗證商品池、排序與回饋，後續逐步銜接 full real-time 能力。","method":"Trend Score / Growth Rate / External Trend Mapping / Anomaly Detection","output":"近期熱議商品清單、趨勢分數、外部話題映射與促銷時機提示。"},
  "reco_infinite": {"id":"reco_infinite","milestone":"M4","is_anchor":false,"lane":"recommendation","laneTitle":"推薦機制","sprint":"Sprint 10–11","title":"無限滾動推薦（session-based / near real-time）","tags":["R","B","I"],"phase":"Phase 2 → 4","deps":["reco_similar","df_browse_events","search_app_launch"],"enables":["reco_context"],"validation":["推薦曝光後 CTR 是否高於原排序商品","推薦商品進入詳情頁、收藏、booking_start 的增量","熱門分數是否排除高曝光污染"],"limit":"即時推薦屬後續成熟能力；初期先以 batch / session-based 能力驗證商品池、排序與回饋，再逐步銜接 event streaming、online feature 與低延遲服務。","initial":"初期以 batch / session-based 驗證商品池、排序與回饋，後續逐步銜接 full real-time 能力。","method":"Session-based Recommendation / Sequential Recommendation / Near Real-time Features / Multi-objective Ranking","output":"當次 session 的下一批推薦商品、排序分數與推薦理由。"},
  "reco_context": {"id":"reco_context","milestone":"M4","is_anchor":false,"lane":"recommendation","laneTitle":"推薦機制","sprint":"Sprint 12–13","title":"情境推薦（視事件階段成熟度推進）","tags":["R","B","I"],"phase":"Phase 2 → 4","deps":["reco_infinite","reco_segment_content","df_decision_info"],"enables":["act_script_reward"],"validation":["推薦曝光後 CTR 是否高於原排序商品","推薦商品進入詳情頁、收藏、booking_start 的增量","熱門分數是否排除高曝光污染"],"limit":"即時推薦屬後續成熟能力；初期先以 batch / session-based 能力驗證商品池、排序與回饋，再逐步銜接 event streaming、online feature 與低延遲服務。","initial":"初期以 batch / session-based 驗證商品池、排序與回饋，後續逐步銜接 full real-time 能力。","method":"Contextual Recommendation / Intent Score / Lifecycle Stage Rule / Trigger Eligibility","output":"情境推薦清單、觸發條件、適用事件階段與排除條件。"},
  "cross_related": {"id":"cross_related","milestone":"M4","is_anchor":true,"lane":"cross_sell","laneTitle":"交叉銷售","sprint":"Sprint 8–9","title":"關聯性商品銷售推薦（銜接 MVP 上線後優化）","tags":["A","I","R"],"phase":"Phase 4","deps":["reco_similar","act_stage_label"],"enables":["dt_pretrip","dt_posttrip"],"validation":["加購品曝光後 CTR 與轉換率","加購推薦是否符合訂單狀態與可售性","推送後客服負擔、取消與干擾成本是否升高"],"limit":"交叉銷售會依旅程階段、可售狀態、頻控、服務負荷與同意狀態進行控管。","initial":"先以商品關聯規則與加購場景驗證，再逐步導入旅程階段、可售性與頻控。","method":"Association Rule / Apriori / FP-Growth / Market Basket Analysis / Eligibility Rule","output":"關聯商品、加購推薦、適用條件與可售性檢查結果。"},
  "cross_decision_pref": {"id":"cross_decision_pref","milestone":"M4","is_anchor":false,"lane":"cross_sell","laneTitle":"交叉銷售","sprint":"Sprint 9–10","title":"歷史決策偏好商品推薦（依據決策類型）","tags":["A","I","R"],"phase":"Phase 4","deps":["df_decision_info","act_stage_label"],"enables":["cross_lookalike"],"validation":["加購品曝光後 CTR 與轉換率","加購推薦是否符合訂單狀態與可售性","推送後客服負擔、取消與干擾成本是否升高"],"limit":"交叉銷售會依旅程階段、可售狀態、頻控、服務負荷與同意狀態進行控管。","initial":"先以商品關聯規則與加購場景驗證，再逐步導入旅程階段、可售性與頻控。","method":"Lifecycle Recommendation / Contextual Ranking / Decision Preference Mapping / Next Best Offer","output":"依決策類型與旅程階段產生的 Next Best Offer 與推薦理由。"},
  "cross_lookalike": {"id":"cross_lookalike","milestone":"M4","is_anchor":false,"lane":"cross_sell","laneTitle":"交叉銷售","sprint":"Sprint 12–13","title":"類似受眾促銷（Lookalike）","tags":["A","I","R"],"phase":"Phase 4","deps":["cross_decision_pref","ads_signal_gateway","act_active_grade"],"enables":[],"validation":["加購品曝光後 CTR 與轉換率","加購推薦是否符合訂單狀態與可售性","推送後客服負擔、取消與干擾成本是否升高"],"limit":"交叉銷售會依旅程階段、可售狀態、頻控、服務負荷與同意狀態進行控管。","initial":"先以商品關聯規則與加購場景驗證，再逐步導入旅程階段、可售性與頻控。","method":"Lookalike Seed / Audience Scoring / Propensity-based Audience Seed / Match Rate Monitoring / Holdout Evaluation","output":"類似受眾種子包、促銷名單、匹配率與投放增量觀測資料。"},
  "act_segment_push": {"id":"act_segment_push","milestone":"M2","is_anchor":true,"lane":"activation","laneTitle":"用戶活化","sprint":"Sprint 7–8","title":"App 分眾推播（ID-based，手動設定）","tags":["I","P","A","G"],"phase":"Phase 2 → 5","deps":["df_login_events","df_marketing_events"],"enables":[],"validation":["推播開啟率、點擊率與後續行為轉換","高意圖未轉換名單召回率","自動化觸發後的干擾成本與退訂率"],"limit":"活化可由規則型能力先行；自動化決策、Propensity 與 ROI 最佳化會隨資料累積與回饋穩定逐步推進。","initial":"先以 ID-based、人工規則、固定情境與小範圍自動化驗證；模型型分眾與 Propensity 後續補上。","method":"ID-based Segmentation / Rule Engine / Rule-based Send-time Selection / Frequency Capping","output":"手動分眾推播名單、推播條件、排除條件與頻控設定。"},
  "act_stage_label": {"id":"act_stage_label","milestone":"M5","is_anchor":false,"lane":"activation","laneTitle":"用戶活化","sprint":"Sprint 8–9","title":"行為階段分層標籤化，支援行前銷售情境露出","tags":["I","P","A","G"],"phase":"Phase 2 → 5","deps":["df_browse_events","df_purchase_events","df_cold_start"],"enables":["cross_related","cross_decision_pref","act_active_grade","act_script_reward","dt_pretrip"],"validation":["推播開啟率、點擊率與後續行為轉換","高意圖未轉換名單召回率","自動化觸發後的干擾成本與退訂率"],"limit":"活化可由規則型能力先行；自動化決策、Propensity 與 ROI 最佳化會隨資料累積與回饋穩定逐步推進。","initial":"先以 ID-based、人工規則、固定情境與小範圍自動化驗證；模型型分眾與 Propensity 後續補上。","method":"Rule-based Lifecycle Stage Labeling / Intent Score / Product Affinity Score / Lifecycle Stage Mapping","output":"行為階段標籤、行前銷售情境條件與高意圖未轉換名單。"},
  "act_active_grade": {"id":"act_active_grade","milestone":"M5","is_anchor":false,"lane":"activation","laneTitle":"用戶活化","sprint":"Sprint 9–10","title":"細化活躍度分級，優化有效名單撈取機制","tags":["I","P","A","G"],"phase":"Phase 2 → 5","deps":["act_stage_label","df_decision_info"],"enables":["cross_lookalike","act_script_push","act_script_reward","act_ai_audience"],"validation":["推播開啟率、點擊率與後續行為轉換","高意圖未轉換名單召回率","自動化觸發後的干擾成本與退訂率"],"limit":"活化可由規則型能力先行；自動化決策、Propensity 與 ROI 最佳化會隨資料累積與回饋穩定逐步推進。","initial":"先以 ID-based、人工規則、固定情境與小範圍自動化驗證；模型型分眾與 Propensity 後續補上。","method":"RFM / Engagement Score / Logistic Regression / LightGBM / Threshold Calibration","output":"活躍度分級、有效名單排序、轉換傾向候選分數。"},
  "act_script_push": {"id":"act_script_push","milestone":"M5","is_anchor":false,"lane":"activation","laneTitle":"用戶活化","sprint":"Sprint 10–11","title":"自動化腳本互動：推播通知（固定時間召回）","tags":["I","P","A","G"],"phase":"Phase 2 → 5","deps":["act_active_grade","df_marketing_events"],"enables":["act_ai_audience"],"validation":["推播開啟率、點擊率與後續行為轉換","高意圖未轉換名單召回率","自動化觸發後的干擾成本與退訂率"],"limit":"活化可由規則型能力先行；自動化決策、Propensity 與 ROI 最佳化會隨資料累積與回饋穩定逐步推進。","initial":"先以 ID-based、人工規則、固定情境與小範圍自動化驗證；模型型分眾與 Propensity 後續補上。","method":"Rule Engine / Scheduled Trigger / Response Propensity / Frequency Capping / Stop-loss Rule","output":"固定時間召回腳本、觸發名單、推播頻控與回應觀測資料。"},
  "act_script_reward": {"id":"act_script_reward","milestone":"M5","is_anchor":false,"lane":"activation","laneTitle":"用戶活化","sprint":"Sprint 12–13","title":"自動化腳本互動：站內行為獎勵（條件式觸發）","tags":["I","P","A","G"],"phase":"Phase 2 → 5","deps":["act_active_grade","act_stage_label","reco_context"],"enables":["act_ai_audience"],"validation":["推播開啟率、點擊率與後續行為轉換","高意圖未轉換名單召回率","自動化觸發後的干擾成本與退訂率"],"limit":"活化可由規則型能力先行；自動化決策、Propensity 與 ROI 最佳化會隨資料累積與回饋穩定逐步推進。","initial":"先以 ID-based、人工規則、固定情境與小範圍自動化驗證；模型型分眾與 Propensity 後續補上。","method":"Event-based Rule Engine / Conditional Trigger / Reward Eligibility / Stop-loss Rule / Uplift Observation","output":"站內行為獎勵觸發條件、適用名單、排除名單與增量觀測資料。"},
  "act_ai_audience": {"id":"act_ai_audience","milestone":"M5","is_anchor":false,"lane":"activation","laneTitle":"用戶活化","sprint":"Sprint 15–16","title":"AI 輔助設定受眾，滾動更新受眾包","tags":["I","P","A","G"],"phase":"Phase 2 → 5","deps":["act_active_grade","df_id_mapping","act_script_push","act_script_reward"],"enables":[],"validation":["推播開啟率、點擊率與後續行為轉換","高意圖未轉換名單召回率","自動化觸發後的干擾成本與退訂率"],"limit":"活化可由規則型能力先行；自動化決策、Propensity 與 ROI 最佳化會隨資料累積與回饋穩定逐步推進。","initial":"先以 ID-based、人工規則、固定情境與小範圍自動化驗證；模型型分眾與 Propensity 後續補上。","method":"AI-assisted Audience Builder / Rule Generation / Propensity-based Audience Seed / Human-in-the-loop Review / Rolling Refresh","output":"AI 輔助受眾條件草案、滾動更新受眾包與人工審核紀錄。"},
  "ads_capi": {"id":"ads_capi","milestone":"M4","is_anchor":true,"lane":"ads","laneTitle":"站外廣告投放","sprint":"Sprint 8–9","title":"Conversions API Event Streaming（第一方自訂事件送至 Meta）","tags":["O","I","P"],"phase":"Phase 4","deps":["df_marketing_events","df_purchase_events","df_login_events"],"enables":["ads_signal_gateway"],"validation":["事件回傳成功率與去重品質","受眾匹配率與更新頻率","高意圖受眾與一般受眾的投放差異"],"limit":"透過回接成效回饋，投放能力可由受眾輸出升級為可驗證增量的閉環。","initial":"先打通第一方事件與受眾輸出，再讓高意圖、高價值與類似受眾作為投放增量驗證。","method":"Conversion Feedback / Event Deduplication / Match Rate Monitoring / Server-side Event Streaming","output":"第一方事件回傳、去重監測、事件成功率與 Meta 回饋資料。"},
  "ads_signal_gateway": {"id":"ads_signal_gateway","milestone":"M4","is_anchor":false,"lane":"ads","laneTitle":"站外廣告投放","sprint":"Sprint 10–11","title":"Meta Signal Gateway（第一方受眾同步，涵蓋匿名與會員）","tags":["O","I","P"],"phase":"Phase 4","deps":["ads_capi","df_login_events"],"enables":["cross_lookalike"],"validation":["事件回傳成功率與去重品質","受眾匹配率與更新頻率","高意圖受眾與一般受眾的投放差異"],"limit":"透過回接成效回饋，投放能力可由受眾輸出升級為可驗證增量的閉環。","initial":"先打通第一方事件與受眾輸出，再讓高意圖、高價值與類似受眾作為投放增量驗證。","method":"Audience Sync / Identity Resolution / Lookalike Seed / Match Rate Monitoring / Consent Filtering","output":"匿名與會員受眾同步包、高意圖 seed、匹配率與同步狀態。"},
  "dt_pretrip": {"id":"dt_pretrip","milestone":"M5","is_anchor":true,"lane":"digital_twins","laneTitle":"AI 旅程助理","sprint":"Sprint 10–11","title":"AI 旅程助理（行前提醒）","tags":["G","K","O"],"phase":"Phase 5","deps":["search_app_launch","act_stage_label","cross_related"],"enables":["dt_posttrip","dt_intratrip"],"validation":["AI 回覆是否能被 trace 與評估","行前、行中、行後互動是否產生有效行為","工具調用成功率、成本、延遲與異常率"],"limit":"AI 互動層聚焦情境承接、知識組織、工具調用與回覆品質觀測，並銜接搜尋推薦能力。","initial":"先以固定旅遊情境、知識節點、工具調用與回覆品質觀測落地，再逐步個人化。","method":"RAG / Context Routing / Tool Calling / Answer Grounding / Journey Stage Context","output":"行前提醒、行程知識回覆、服務工具調用與回答依據 trace。"},
  "dt_posttrip": {"id":"dt_posttrip","milestone":"M5","is_anchor":false,"lane":"digital_twins","laneTitle":"AI 旅程助理","sprint":"Sprint 12–13","title":"AI 旅程助理（行後互動）","tags":["G","K","O"],"phase":"Phase 5","deps":["dt_pretrip","df_purchase_events","cross_related"],"enables":["dt_intratrip"],"validation":["AI 回覆是否能被 trace 與評估","行前、行中、行後互動是否產生有效行為","工具調用成功率、成本、延遲與異常率"],"limit":"AI 互動層聚焦情境承接、知識組織、工具調用與回覆品質觀測，並銜接搜尋推薦能力。","initial":"先以固定旅遊情境、知識節點、工具調用與回覆品質觀測落地，再逐步個人化。","method":"RAG / Feedback Classification / Sentiment Classification / LLM Evaluation / Trace Review","output":"行後互動、回饋分類、品質評估與可追蹤對話紀錄。"},
  "dt_intratrip": {"id":"dt_intratrip","milestone":"M5","is_anchor":true,"lane":"digital_twins","laneTitle":"AI 旅程助理","sprint":"Sprint 14–15","title":"AI 旅程助理（行中互動）","tags":["G","K","O"],"phase":"Phase 5","deps":["dt_pretrip","dt_posttrip","search_web_launch"],"enables":[],"validation":["AI 回覆是否能被 trace 與評估","行前、行中、行後互動是否產生有效行為","工具調用成功率、成本、延遲與異常率"],"limit":"AI 互動層聚焦情境承接、知識組織、工具調用與回覆品質觀測，並銜接搜尋推薦能力。","initial":"先以固定旅遊情境、知識節點、工具調用與回覆品質觀測落地，再逐步個人化。","method":"Context Routing / Tool Calling / Guardrails / Human Handoff / Runtime Monitoring","output":"行中即時互動、異常處理、轉人工條件與工具調用結果。"}
  };

  export const TASK_DETAILS = {
    "data_foundation": {"method":"Event Taxonomy / Funnel Mapping / Data Quality Check / Identity Resolution","output":"事件規範、漏斗資料集、ID Mapping 與回饋資料。"},
    "ai_search": {"method":"BM25 / Query Rewrite / NER / Intent Classification / Embedding Retrieval / Learning-to-Rank","output":"query intent、候選商品池、facet 條件、排序分數。"},
    "recommendation": {"method":"Time-decay Popularity / Content-based Similarity / Item-to-Item CF / ALS / Session-based Recommendation","output":"熱門分數、相似商品清單、分眾商品池、session 推薦結果。"},
    "cross_sell": {"method":"Association Rule / FP-Growth / Market Basket Analysis / Next Best Offer Ranking","output":"加購推薦清單、NBO、觸發條件、排除條件。"},
    "activation": {"method":"RFM / Intent Score / Propensity Model / Response Propensity / Uplift Modeling / Rule Engine","output":"意圖濃度、活躍度分級、轉換傾向、召回名單。"},
    "ads": {"method":"Audience Scoring / LTV Segment / Lookalike Seed / Conversion Feedback / Holdout Evaluation","output":"高意圖受眾包、高價值 seed、事件回傳、匹配率回饋。"},
    "digital_twins": {"method":"RAG / Knowledge Retrieval / Context Routing / Tool Calling / Agent Workflow / LLM Evaluation","output":"知識節點回覆、工具調用結果、prompt trace、品質評估。"}
  };

  export const TASK_METHOD_OVERRIDES = {
    "df_event_spec": {"core":["Event Taxonomy","Data Contract"],"support":["Funnel Mapping","Naming Convention","Event QA"],"later":["Data Quality Check","Identity Resolution"],"maturity":"Phase 1：先建立事件語言、命名規則與驗收基準。"},
    "df_search_events": {"core":["Search Event Schema","Query Log Structuring"],"support":["SERP Exposure Tracking","Zero-result Tracking"],"later":["Search Quality Evaluation","Relevance Feedback"],"maturity":"Phase 1：先讓搜尋行為可被回收，支援後續搜尋品質與排序驗證。"},
    "df_purchase_events": {"core":["Booking Event Schema","Conversion Funnel Mapping"],"support":["Attribution Feedback","Data Quality Check"],"later":["Conversion Feedback","Holdout Evaluation"],"maturity":"Phase 1：建立轉換回饋，支援推薦、活化與投放閉環。"},
    "df_browse_events": {"core":["Browse Event Schema","Product View Tracking"],"support":["Engagement Depth","Signal Aggregation"],"later":["Intent Score","Product Affinity Score"],"maturity":"Phase 1：先收集瀏覽深度與商品互動訊號，作為推薦與意圖濃度基礎。"},
    "df_marketing_events": {"core":["Campaign Event Schema","UTM Mapping"],"support":["Push Interaction Tracking","Channel Feedback"],"later":["Response Propensity","Audience Scoring"],"maturity":"Phase 1：先把行銷互動與回流可觀測化。"},
    "df_login_events": {"core":["Identity Event Mapping","Consent State Mapping"],"support":["Login Funnel Tracking","Member Linking"],"later":["Identity Resolution","Audience Sync"],"maturity":"Phase 1：先讓登入、會員與同意狀態可支援後續受眾與跨渠道同步。"},
    "df_cold_start": {"core":["Preference Questionnaire","Progressive Profiling"],"support":["Cold-start Feature Encoding","Rule-based Preference Mapping"],"later":["Product Affinity Score","Intent Score"],"maturity":"Phase 1 → 2：以低摩擦偏好收集補足非高頻旅遊場景的冷啟動問題。"},
    "df_decision_info": {"core":["Decision Attribute Collection","Preference Feature Engineering"],"support":["Context Labeling","Intent Feature Mapping"],"later":["Lifecycle Recommendation","Contextual Recommendation"],"maturity":"Phase 1 → 3：將決策理由轉成後續推薦與活化可使用的特徵。"},
    "df_id_mapping": {"core":["Identity Resolution","Device-to-User Stitching"],"support":["Merge Rules","Data Quality Check"],"later":["Audience Sync","Lookalike Seed"],"maturity":"Phase 1 → 4：作為跨裝置、跨渠道、匿名與會員串接的共用基礎。"},
    "search_beta": {"core":["BM25","Query Rewrite","NER"],"support":["Synonym Expansion","Rule-based Facet Mapping"],"later":["Embedding Retrieval","ANN Search","Learning-to-Rank"],"maturity":"Phase 3 初期：先驗證查詢理解與 keyword retrieval，不一次進入完整 hybrid reranking。"},
    "search_trial": {"core":["Search Quality Evaluation","A/B Testing"],"support":["Relevance Feedback","Zero-result Analysis"],"later":["Learning-to-Rank","Cross-Encoder Reranker"],"maturity":"Phase 3 驗證：重點是小流量觀測，而不是新增複雜模型。"},
    "search_vector": {"core":["Embedding Retrieval","ANN Search"],"support":["Hybrid Fusion","Candidate Recall Evaluation"],"later":["Cross-Encoder Reranker","Learning-to-Rank"],"maturity":"Phase 3 中期：將向量召回接入 hybrid search，補足模糊需求與自然語言查詢。"},
    "search_app_launch": {"core":["Hybrid Search","Availability Filter","Facet Filter"],"support":["Learning-to-Rank","Feature Flag Rollout"],"later":["Cross-Encoder Reranker","Ranking Calibration"],"maturity":"Phase 3 上線：以可售性、facet 與排序穩定為主，進階 reranking 依成效推進。"},
    "search_web_launch": {"core":["Web Search Integration","Hybrid Search"],"support":["Ranking Calibration","Search Analytics"],"later":["Cross-Encoder Reranker","Personalized Search"],"maturity":"Phase 3 擴展：將 App 驗證後能力移植到 Web，並做排序校準。"},
    "reco_hot": {"core":["Time-decay Popularity","Wilson Score","Bayesian Smoothing"],"support":["Exposure Correction"],"later":["Multi-objective Ranking","Trend Score"],"maturity":"Phase 2：以批次熱門分數與曝光修正驗證，不等同即時個人化推薦。"},
    "reco_similar": {"core":["Content-based Similarity","Embedding Similarity"],"support":["Item-to-Item CF","Similarity Thresholding"],"later":["ALS / Matrix Factorization","Session-based Recommendation"],"maturity":"Phase 3：先由內容與商品相似性建立可控推薦，再逐步加入行為共現。"},
    "reco_segment_content": {"core":["Rule-based Segmentation","ID-based Audience Matching"],"support":["Content-based Recommendation","Manual Slot Control"],"later":["Product Affinity Score","Propensity Model"],"maturity":"Phase 2：以人工條件與 ID-based 版位控管驗證分眾內容價值。"},
    "reco_trend": {"core":["Trend Score","Growth Rate","External Trend Mapping"],"support":["Anomaly Detection"],"later":["Multi-objective Ranking","Contextual Recommendation"],"maturity":"Phase 3：補上外部趨勢與近期熱度，避免只看歷史熱門。"},
    "reco_infinite": {"core":["Session-based Recommendation","Sequential Recommendation"],"support":["Near Real-time Features","Multi-objective Ranking"],"later":["Contextual Recommendation","Propensity Model"],"maturity":"Phase 4：開始走向 session-based / near real-time，但仍以可控排序與回饋為主。"},
    "reco_context": {"core":["Contextual Recommendation","Intent Score"],"support":["Lifecycle Stage Rule","Trigger Eligibility"],"later":["Next Best Offer","Contextual Bandit"],"maturity":"Phase 4：從商品推薦升級為情境、階段與觸發條件共同決定。"},
    "cross_related": {"core":["Association Rule","Apriori","FP-Growth"],"support":["Market Basket Analysis","Eligibility Rule"],"later":["Lifecycle Recommendation","Next Best Offer"],"maturity":"Phase 4 初期：先驗證商品關聯與加購規則，不直接跳到全旅程 NBO。"},
    "cross_decision_pref": {"core":["Lifecycle Recommendation","Decision Preference Mapping"],"support":["Contextual Ranking","Next Best Offer"],"later":["Contextual Bandit","Uplift Modeling"],"maturity":"Phase 4：將歷史決策偏好與旅程階段納入 Next Best Offer。"},
    "cross_lookalike": {"core":["Lookalike Seed","Audience Scoring"],"support":["Propensity-based Audience Seed","Match Rate Monitoring","Holdout Evaluation"],"later":["LTV Segment","Uplift Modeling"],"maturity":"Phase 4：以高品質 seed 和受眾回饋驗證站外增量。"},
    "act_segment_push": {"core":["ID-based Segmentation","Rule Engine"],"support":["Rule-based Send-time Selection","Frequency Capping"],"later":["Response Propensity","Uplift Modeling"],"maturity":"Phase 2：先以人工規則與 ID-based 名單控管，避免過早模型化。"},
    "act_stage_label": {"core":["Rule-based Lifecycle Stage Labeling","Intent Score"],"support":["Product Affinity Score","Lifecycle Stage Mapping"],"later":["Propensity Model","Contextual Recommendation"],"maturity":"Phase 3：把行為階段結構化，支援行前銷售與後續自動化。"},
    "act_active_grade": {"core":["RFM","Engagement Score"],"support":["Logistic Regression","LightGBM","Threshold Calibration"],"later":["Response Propensity","Uplift Modeling"],"maturity":"Phase 4：從活躍度分級逐步銜接轉換傾向模型。"},
    "act_script_push": {"core":["Rule Engine","Scheduled Trigger"],"support":["Response Propensity","Frequency Capping","Stop-loss Rule"],"later":["Uplift Modeling","Contextual Bandit"],"maturity":"Phase 4：先做固定時間召回與頻控，再觀察回應傾向與干擾成本。"},
    "act_script_reward": {"core":["Event-based Rule Engine","Conditional Trigger"],"support":["Reward Eligibility","Stop-loss Rule","Uplift Observation"],"later":["Uplift Modeling","Next Best Action"],"maturity":"Phase 4：以條件式觸發建立站內行為獎勵與增量觀測。"},
    "act_ai_audience": {"core":["AI-assisted Audience Builder","Rule Generation"],"support":["Propensity-based Audience Seed","Human-in-the-loop Review","Rolling Refresh"],"later":["Autonomous Optimization","Uplift Modeling"],"maturity":"Phase 5：AI 輔助產生受眾條件，但仍保留人工審核與安全邊界。"},
    "ads_capi": {"core":["Server-side Event Streaming","Conversion Feedback"],"support":["Event Deduplication","Match Rate Monitoring"],"later":["Holdout Evaluation","Propensity-based Audience Seed"],"maturity":"Phase 4：先打通第一方事件回傳與去重，再評估投放增量。"},
    "ads_signal_gateway": {"core":["Audience Sync","Identity Resolution"],"support":["Lookalike Seed","Match Rate Monitoring","Consent Filtering"],"later":["LTV Segment","Holdout Evaluation"],"maturity":"Phase 4：把匿名與會員受眾同步出去，並控管同意狀態與匹配率。"},
    "dt_pretrip": {"core":["RAG","Context Routing","Tool Calling"],"support":["Answer Grounding","Journey Stage Context"],"later":["Agent Workflow","Personalization"],"maturity":"Phase 5 初期：先用行前情境與知識節點承接服務需求。"},
    "dt_posttrip": {"core":["RAG","Feedback Classification"],"support":["Sentiment Classification","LLM Evaluation","Trace Review"],"later":["Recommendation Feedback","Lifecycle Recommendation"],"maturity":"Phase 5：把行後互動回饋轉成可評估與可回收的知識與品質資料。"},
    "dt_intratrip": {"core":["Context Routing","Tool Calling","Guardrails"],"support":["Human Handoff","Runtime Monitoring"],"later":["Agent Workflow","Autonomous Tool Use"],"maturity":"Phase 5：行中互動以安全邊界、轉人工與即時監控為優先。"}
  };
  // 把 TASKS 暴露給外部 phase 點亮模組讀取

  export const METHOD_DESCRIPTIONS = {
    "event taxonomy": "定義事件分類、命名與層級，讓後續追蹤與分析有共同語言。",
    "funnel mapping": "將關鍵流程拆成可追蹤步驟，用於觀察流失與轉換。",
    "data quality check": "檢查事件完整性、重複、缺漏與異常，避免模型與報表被髒資料影響。",
    "identity resolution": "整合匿名裝置、會員與跨渠道 ID，建立更穩定的使用者識別。",
    "attribution feedback": "回收行銷與轉換回饋，支援成效歸因與投放優化。",
    "naming convention": "統一事件、參數與物件命名，降低跨團隊維護成本。",
    "event qa": "驗證事件是否依規格觸發、帶值與回收。",
    "data contract": "定義資料生產與消費方的欄位、語意與品質承諾。",
    "search event schema": "定義搜尋行為需要回收的 query、曝光、點擊、改搜與查無結果欄位。",
    "query log structuring": "將搜尋紀錄整理成可分析、可訓練、可回饋的結構。",
    "serp exposure tracking": "追蹤搜尋結果頁商品曝光，避免只看點擊而忽略排序位置。",
    "zero-result tracking": "記錄查無結果情境，支援字典、facet 與召回補強。",
    "booking event schema": "定義 booking_start、訂單與成交相關事件資料。",
    "conversion funnel mapping": "將瀏覽到下訂轉換流程拆成可衡量漏斗。",
    "browse event schema": "定義瀏覽、停留、商品互動與收藏等行為資料。",
    "engagement depth": "衡量使用者瀏覽深度與互動強度。",
    "product view tracking": "追蹤商品頁曝光與進入詳情頁行為。",
    "signal aggregation": "彙整多種行為訊號，形成推薦與活化可使用的特徵。",
    "campaign event schema": "定義行銷活動、推播與回流需要追蹤的事件資料。",
    "utm mapping": "將來源、媒介與活動參數對齊到行銷成效分析。",
    "push interaction tracking": "追蹤推播送達、開啟、點擊與後續行為。",
    "channel feedback": "回收不同通路互動結果，支援跨渠道判斷。",
    "identity event mapping": "把登入、註冊、匿名與會員事件對齊到同一識別流程。",
    "consent state mapping": "記錄使用者同意狀態，避免不合規資料使用。",
    "login funnel tracking": "追蹤登入與註冊流程中的流失與完成。",
    "member linking": "將匿名行為與會員身份銜接。",
    "preference questionnaire": "用低摩擦問題收集冷啟動偏好。",
    "progressive profiling": "分階段補齊使用者偏好，避免一次詢問過多。",
    "cold-start feature encoding": "將新用戶偏好轉成推薦或分眾可用特徵。",
    "rule-based preference mapping": "用規則將問卷或互動答案對應到偏好標籤。",
    "decision attribute collection": "收集預算、同行者、旅遊動機等決策因素。",
    "preference feature engineering": "將偏好與決策資訊加工成模型或規則可用特徵。",
    "context labeling": "標記使用者所處情境，例如行前、比價、猶豫或回訪。",
    "intent feature mapping": "將行為與情境轉成意圖相關特徵。",
    "device-to-user stitching": "將裝置層行為連到使用者或會員層。",
    "merge rules": "定義多個 ID 合併或排除的規則。",
    "bm25": "關鍵字檢索基礎排序，適合處理明確目的地、商品名與主題詞。",
    "synonym expansion": "擴充同義詞與常見查詢變體，提升關鍵字召回率。",
    "query rewrite": "將自然語言查詢改寫成更適合搜尋引擎理解的查詢條件。",
    "ner": "辨識目的地、POI、天數、月份、價格等查詢實體。",
    "intent classification": "判斷查詢或對話背後的需求類型，例如找商品、問行程或需要服務。",
    "rule-based facet mapping": "用規則把查詢意圖對應到目的地、天數、價格帶等 facet。",
    "search quality evaluation": "用 CTR、zero-result、zero-click、改搜率等評估搜尋品質。",
    "a/b testing": "以控制組與變異組比較改動是否產生有效提升。",
    "relevance feedback": "回收點擊、停留、改搜等行為作為搜尋相關性回饋。",
    "zero-result analysis": "分析查無結果原因，判斷是字典、商品資料、facet 還是召回問題。",
    "embedding retrieval": "用語意相似度找出不完全命中關鍵字但需求相近的商品。",
    "ann search": "用近似最近鄰搜尋提升向量召回效率。",
    "hybrid fusion": "融合關鍵字與向量召回結果，兼顧精準詞與自然語言需求。",
    "candidate recall evaluation": "評估候選商品池是否涵蓋足夠相關結果。",
    "learning-to-rank": "以特徵與回饋訓練排序模型，改善結果排序。",
    "cross-encoder reranker": "對召回結果做更精細的語意相關性重排。",
    "hybrid search": "結合關鍵字、語意召回、條件過濾與排序的搜尋方式。",
    "availability filter": "先排除不可售、無庫存或不符合條件的商品。",
    "facet filter": "依目的地、日期、天數、價格等條件過濾商品。",
    "feature flag rollout": "用開關控制功能分批上線與回滾。",
    "ranking calibration": "校準排序分數，避免單一訊號過度影響結果。",
    "web search integration": "將已驗證的搜尋能力整合到 Web 端。",
    "search analytics": "持續追蹤搜尋品質、流量與轉換結果。",
    "personalized search": "依使用者偏好與歷史行為調整搜尋結果。",
    "time-decay popularity": "讓近期互動比久遠互動有更高權重，避免熱門榜過度陳舊。",
    "wilson score": "在樣本量不足時降低極端比例誤判，讓熱門排序更穩定。",
    "bayesian smoothing": "用先驗校正小樣本波動，避免少量高 CTR 商品被過度放大。",
    "exposure correction": "修正高曝光商品自然累積更多點擊的偏誤。",
    "multi-objective ranking": "同時考慮 CTR、轉換、毛利、可售性與體驗等多目標排序。",
    "trend score": "衡量近期成長、外部熱度或促銷時機帶來的趨勢強度。",
    "content-based similarity": "依商品內容、地區、主題、天數等屬性找相似商品。",
    "embedding similarity": "以向量表示比較商品或需求的語意相似度。",
    "item-to-item cf": "根據使用者共同行為找出常被一起瀏覽或點擊的商品。",
    "similarity thresholding": "設定相似度門檻，避免推薦過度鬆散或不相關商品。",
    "als / matrix factorization": "用矩陣分解從使用者與商品互動中學習潛在偏好。",
    "session-based recommendation": "根據當次瀏覽行為即時調整推薦。",
    "rule-based segmentation": "用明確條件建立分眾，適合初期可控驗證。",
    "id-based audience matching": "以會員或裝置 ID 對應到特定分眾名單。",
    "content-based recommendation": "根據商品與內容屬性推薦符合偏好的項目。",
    "manual slot control": "由營運或行銷手動控制版位與推薦條件。",
    "product affinity score": "估算使用者對特定商品、目的地或主題的偏好強度。",
    "propensity model": "預測使用者採取特定行動的機率，例如點擊、收藏或下訂。",
    "growth rate": "衡量商品或需求在短期內的成長速度。",
    "external trend mapping": "將外部熱議、搜尋趨勢或活動話題對應到內部商品。",
    "anomaly detection": "偵測不尋常的熱度變化或資料異常。",
    "sequential recommendation": "根據行為順序預測下一個可能感興趣的商品。",
    "near real-time features": "接近即時更新的行為或情境特徵，用於推薦或活化。",
    "contextual recommendation": "把使用者情境、旅程階段與商品條件納入推薦。",
    "lifecycle stage rule": "依旅程或訂單階段設定觸發規則。",
    "trigger eligibility": "判斷某次推薦或觸發是否符合條件。",
    "association rule": "找出常一起購買、瀏覽或加購的商品關聯。",
    "apriori": "常見關聯規則演算法，用於發現商品組合關係。",
    "fp-growth": "更有效率的頻繁項目集挖掘方法。",
    "market basket analysis": "分析商品之間的共購或加購關係。",
    "eligibility rule": "判斷使用者或訂單是否符合特定推薦、加購或觸發資格。",
    "lifecycle recommendation": "依旅程階段與訂單狀態調整推薦內容。",
    "next best offer": "在當前情境下選出最合適的優惠、商品或加購建議。",
    "decision preference mapping": "把歷史決策因素對應到可能偏好的商品或服務。",
    "contextual ranking": "根據情境、條件與商品屬性進行排序。",
    "contextual bandit": "在探索與利用之間動態調整推薦或觸發策略。",
    "lookalike seed": "用高價值或高意圖族群作為類似受眾擴展基礎。",
    "audience scoring": "為受眾打分，判斷其價值、意圖或可投放程度。",
    "propensity-based audience seed": "以高轉換傾向族群作為站外投放或類似受眾種子。",
    "match rate monitoring": "監測受眾同步到廣告平台後的匹配率。",
    "holdout evaluation": "保留不觸發或不投放的對照組，用於觀察增量效果。",
    "ltv segment": "依長期價值區分受眾，支援高價值投放或維繫。",
    "rfm": "用近期互動、頻率與價值衡量使用者活躍度。",
    "engagement score": "整合瀏覽、點擊、收藏、停留等互動強度。",
    "logistic regression": "常見可解釋分類模型，適合建立初版傾向分數。",
    "lightgbm": "梯度提升樹模型，適合處理結構化特徵與非線性關係。",
    "xgboost": "梯度提升樹模型，常用於轉換傾向或排序特徵建模。",
    "lightgbm / xgboost": "常見樹模型，適合處理結構化特徵與轉換傾向預測。",
    "threshold calibration": "調整分數門檻，讓名單量、精準度與干擾成本取得平衡。",
    "response propensity": "預測使用者對推播、提醒或促銷的回應機率。",
    "uplift modeling": "評估觸發溝通後是否真的帶來增量，而不是只找原本就會轉換的人。",
    "id-based segmentation": "以使用者 ID 建立可觸達的分眾名單。",
    "rule engine": "用規則引擎管理分眾、觸發、排除與頻控條件。",
    "rule-based send-time selection": "用規則選擇較適合發送的時間點。",
    "frequency capping": "限制觸發或推播頻率，降低干擾與退訂風險。",
    "rule-based lifecycle stage labeling": "用規則標記使用者或訂單所處旅程階段。",
    "lifecycle stage mapping": "將行為、訂單與時間點對應到旅程階段。",
    "scheduled trigger": "依固定時間或排程觸發溝通。",
    "conditional trigger": "符合特定條件時才觸發提醒、優惠或互動。",
    "event-based rule engine": "根據事件發生與條件規則執行觸發。",
    "reward eligibility": "判斷使用者是否符合特定獎勵或優惠觸發資格。",
    "stop-loss rule": "當成效不佳、頻率過高或風險升高時停止觸發。",
    "uplift observation": "先觀察觸發前後增量訊號，作為正式 uplift modeling 前的基礎。",
    "next best action": "在當前情境下選擇最合適的下一步行動，不限於優惠或商品。",
    "ai-assisted audience builder": "由 AI 輔助產生受眾條件草案，但仍保留人工審核。",
    "rule generation": "產生可執行的分眾、排除或觸發規則草案。",
    "human-in-the-loop review": "讓人工保留審核與調整權，避免自動化誤判直接上線。",
    "rolling refresh": "定期更新受眾或分數，避免名單過期。",
    "autonomous optimization": "由系統自動調整策略，屬後續成熟能力而非初期承諾。",
    "server-side event streaming": "從伺服器端回傳事件，提高穩定性與資料控制。",
    "conversion feedback": "回收轉換結果，讓投放與模型能形成閉環。",
    "event deduplication": "避免同一事件被前端與後端重複計算。",
    "audience sync": "將內部受眾同步到外部平台或行銷工具。",
    "consent filtering": "依使用者同意狀態過濾可使用或可同步資料。",
    "rag": "以知識庫檢索結果輔助 AI 回覆，降低憑空生成風險。",
    "knowledge retrieval": "從知識庫或文件中找出與問題相關的內容。",
    "context routing": "根據旅程階段、問題類型或使用者狀態選擇合適流程。",
    "tool calling": "讓 AI 在需要時呼叫系統工具或 API 執行任務。",
    "answer grounding": "要求回覆依據可追蹤資料或知識來源。",
    "journey stage context": "將行前、行中、行後等旅程狀態納入 AI 回覆。",
    "agent workflow": "多步驟 AI 任務流程，通常包含判斷、工具調用與結果檢查。",
    "personalization": "依使用者偏好或情境調整回覆與服務。",
    "feedback classification": "將使用者回饋分類，支援服務改善與後續分析。",
    "sentiment classification": "判斷回饋或對話中的情緒傾向。",
    "llm evaluation": "評估 AI 回覆品質、正確性、可用性與風險。",
    "trace review": "檢視 AI 回覆過程、檢索內容與工具調用紀錄。",
    "recommendation feedback": "把互動或回饋反向用於推薦品質改善。",
    "guardrails": "設定安全、品質與業務規則邊界，降低錯誤回覆風險。",
    "human handoff": "在高風險或無法處理時轉由人工服務承接。",
    "runtime monitoring": "監控 AI 服務執行中的成本、延遲、錯誤與異常。",
    "autonomous tool use": "讓 AI 更自主地選擇與操作工具，屬後續成熟能力。"
  };

  export const TAGS = {"D":["Data Readiness","資料準備"],"O":["Measurement","成效衡量"],"S":["Search","搜尋理解"],"H":["Hybrid","混合召回"],"R":["Recommendation","推薦能力"],"B":["Batch","批次產出"],"I":["Intent","意圖濃度"],"P":["Propensity","傾向分數"],"A":["Automation","自動化觸發"],"G":["AI Agent","代理流程"],"K":["Knowledge","知識節點"]};
